version: "2.2"
services:
  planner:
    build:
      context: ./planner
    image: planner
    networks:
      - webproxy
    depends_on: 
      - worker
  worker:
    build:
      context: ./worker
    image: worker
    networks:
      - webproxy
networks:
  webproxy:
    driver: bridge